twitter:
  track:
    - cryosphereband #if anyone tweets about "cryosphereband"
  follow:
    - "1050383420960980998" #cryosphereband userid
  blacklist: #User ID's
    - "123123123"
    - "456456456"
    - "789789789"
